apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort | default "" }}
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}
